### ISSUE TITLE
"Extract everything" doesn't work

### ISSUE THREAD

**Issue by LinUwUxCat** [Luca1991/NDSFactory#13]
Description of the problem : The "Extract Everything" button doesn't work, altho extracting everything with each button is functional. 
Tested with : TrackMania DS Europe
Problem : The extract everything button first asks to choose a directory, then an window saying "error during the extraction!" appears. No error message appears in the terminal. 
![image](https://user-images.githubusercontent.com/46047705/114278863-0a7df000-9a32-11eb-87b0-6bf8281784c2.png)
Platform : Pop!_OS 20.10
App version : NDSFactory V1.0 rev 319d0e2, build date Apr 7 2021

**Comment by Luca1991** [comment]
This is a pretty good and well organized bug report. If only my colleagues at work would use this precision in asking help, my life would be a lot easier :P 

Back on the issue: I'll look at it ASAP. Can you share your rom md5 please?  thanks. (ONLY md5, NO BINS pls).


EDIT:
It looks like this game has an overlay. Roms with overlay are currently *NOT* supported. 
Please check if "ARM9 Overlay Address" is > than 0. If so, this rom is currently not supported (it is written in the readme). 

I'm currently planning to add FAT extraction/creation feature. In the future I'll try to support roms with overlay, but other features have priority ;)

Closing this as invalid, please feel free to open again if you can't extract roms without overlay.

**Comment by LinUwUxCat** [comment]
> It looks like this game has an overlay. Roms with overlay are currently NOT supported.\

Oops, i did not see that! The rom indeed does have an overlay. Sorry!
