### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by MrButterfingersss** [Luca1991/NDSFactory#15]
ok can this be ported to windows if you can please do i idk how to use it if im on windows and im on windows

**Comment by Luca1991** [comment]
Hello,
the windows executable is available to download from the release section.

Direct download link of the latest autobuild: https://github.com/Luca1991/NDSFactory/releases/download/autobuild/NDSFactory_AUTOBUILD__Windows_x86_64.zip

Closing this issue as won’t fix
