### ISSUE TITLE
[Feature] Setting to toggle light / dark theme

### ISSUE THREAD

**Issue by master801** [Luca1991/NDSFactory#17]
The light / dark theme in the GUI should not be dependent on the OS settings, but instead be a configurable option within the program itself.

Release v1.1-Windows-x64, Windows 10

**Comment by Luca1991** [comment]
Hi @master801 

I really believe that GUI applications should adapt to the OS theme to maintain a consistent look. This is actually the default behavior in Qt. That said, adding an option to allow the user to customize the window theme should be doable without much effort, so I'll keep that in mind for future releases.

thanks.

**Comment by Luca1991** [comment]
Theme selector implemented in commit [4b886a9](https://github.com/Luca1991/NDSFactory/commit/4b886a903378d31b47b14e8be2069ae184c92ec3)

If you don't want to compile it yourself, you can wait for the next release

**Comment by Luca1991** [comment]
Fixed in release v1.2
