### ISSUE TITLE
[Bug] Drop-down menu contents appears on different screen

### ISSUE THREAD

**Issue by master801** [Luca1991/NDSFactory#18]
If the program window is moved over to a different screen (ex screen 2), and "File" menu (happens with "Help" as well) is selected, the contents of the drop-down menu are displayed on the main screen (ex screen 1) instead of the screen the window was moved over to.

Release v1.1-Windows-x64, Windows 10, 3 monitors side-by-side

**Comment by Luca1991** [comment]
Hi @master801 

I can't reproduce this issue because I only have one monitor. Can you check if this problem is also present in other Qt based applications?

Thanks..

**Comment by master801** [comment]
This does indeed seem to be an issue within Qt6 itself. Maybe even within the specific version of Qt6 that NDSFactory v1.1 is packed with.

I tested with OpenRGB and it has the same bug.

So I tried using an older version of NDSFactory (some build from 2021 that uses Qt5), and the combobox issue is not present there.

<details>
<summary>Long probably off-topic thought process</summary>
Which got me thinking, why is it present in one version of Qt5, but not the other. So I compared DLL versions between the two, and found out that OpenRGB uses 5.15.0, while NDSFactory used 5.15.2. Which got me thinking again, if I transplanted the 5.15.2 DLLs to OpenRGB, if the problem would be fixed.

Turns out I was right. Transplanting the 5.15.2 DLLs fixed the combobox issue.
</details>

Testing with Dolphin (the emulator - which also uses Qt6), there are no issues with the combobox drop-down menus there. Interestingly enough, they use `6.5.1` while NDSFactory uses `6.5.2`.

Using the same DLL transplant technique, it seems that the multiple monitor combobox issue has been fixed in NDSFactory, using Dolphin's Qt6 `6.5.1` DLLs.

Before transplanting `6.5.1` (`6.5.2`):
![Screenshot_34](https://github.com/user-attachments/assets/8d799806-fbf0-4f18-bbaa-ded1090a8873)

After transplanting `6.5.1` (`6.5.1`):
![Screenshot_35](https://github.com/user-attachments/assets/8a955c30-d9d3-4806-a0e9-b02f8cec91f5)

It seems this "multiple monitor" issue has been mentioned a lot in the past just looking at Qt's issue tracker, but they seem to have all been closed due to "insufficient" information, or just old age.

EDIT: Yep, this is definitely a bug within `6.5.2` specifically.
https://www.reddit.com/r/QtFramework/comments/17xclf1/qt_652_sucks/

**Comment by Luca1991** [comment]
Hi @master801

On Windows (a macOS) I configured the build server to compile using Qt 6.5.2.
This is the latest LTS release, but I'm starting to consider targeting for the latest stable build.

**Comment by Luca1991** [comment]
We are now using latest stable Qt version for building macOS and Windows version ([d69e4e1](https://github.com/Luca1991/NDSFactory/commit/d69e4e13fa0eb451b6ee36dee3bad50874d090d9))

You can re-test this issue when next NDSFactory release will be available.

**Comment by Luca1991** [comment]
Hi @master801 
this issue should be fixed in release v1.2, as the CI is now building using the last stable Qt version.
Can you test it and let me know if I can close this issue? thanks.

**Comment by master801** [comment]
> Hi @master801 this issue should be fixed in release v1.2, as the CI is now building using the last stable Qt version. Can you test it and let me know if I can close this issue? thanks.

Yes, release v1.2 fixes this issue.

Thanks.
