### ISSUE TITLE
Unable to use any unpacker option

### ISSUE THREAD

**Issue by tugofwardolphin52** [Luca1991/NDSFactory#19]
![Untitled](https://github.com/user-attachments/assets/986bf829-da65-4992-8c1d-c4f8f7fdd4ed)

I'm using the Windows version on Windows 10. Originally I tried to unpack the Pokémon Black rom located at C:\Users\[Username]\Desktop\Games\Roms\DS but all the buttons for the tools are grayed out like in this screenshot. I copied it to the folder that NDSFactory was in to see if it needed to be in there in order to work but it did not fix it. Nothing shows up in the header section either. I have no idea how to get it to just simply work and load up the rom in order to select a tool to use on it since the "load rom" button just fills in the path to the rom and doesn't actually open it. Normally programs will either open the file that you selected or give you an option to open it, which this doesn't do. I'm trying to extract images from the rom and this was one of the tools suggested from search results.

**Comment by Luca1991** [comment]
Hi @tugofwardolphin52 

NDSFactory is working correctly for this game:
![image](https://github.com/user-attachments/assets/0af667e0-01e4-409b-9a3b-f3d68a4220da)

You are probably using a bad dump, please re-dump your game and try again.

**Comment by tugofwardolphin52** [comment]
Thank you. I have verified that it's indeed a bad dump by attempting to load the Spanish, French, Italian and German versions and those did display the header information while the English version didn't.

**Comment by Luca1991** [comment]
No problem, you are welcome :) 

Can I close this issue?

**Comment by tugofwardolphin52** [comment]
Yes please and thank you very much!
