### ISSUE TITLE
Does it run on Raspberry Pi?

### ISSUE THREAD

**Issue by fabianmendes** [Luca1991/NDSFactory#3]

**Comment by Luca1991** [comment]
I'm trying to build it on my Pi 4 right now (building Qt5 atm). Can't promise anything, but I'll try.

**Comment by Luca1991** [comment]
Hey, I can now confirm, it is working on my Raspberry Pi 4 (latest Raspbian).
You have to build Qt using the qt-everywhere release, then install cmake and build NDSFactory.

Here is a screenshot of it running on my Pi:
![screenshot](https://user-images.githubusercontent.com/3731220/108997407-d926ac00-769f-11eb-8e9a-c4a9741153ad.png)

**Comment by fabianmendes** [comment]
Nice! What steps did you?

**Comment by Luca1991** [comment]
@fabianmendes I installed Qt on my Raspberry Pi 4 using this guide: https://www.tal.org/tutorials/building-qt-512-raspberry-pi

Then, just clone this repo an run:
```
mkdir build
cd build
cmake ..
make -j4
```
it should produce a valid executable.

In the future I'll investigate if is possibile to use github actions to build arm bins.

Can I close this issue?

**Comment by fabianmendes** [comment]
yes, thanks!

**Comment by fabianmendes** [comment]
Just to know, why do we need to build a Qt??

**Comment by Luca1991** [comment]
> Just to know, why do we need to build a Qt??

Because there is no prebuild Qt SDK available for Raspberry Pi 4 (you can't build this software without Qt)

**Comment by fabianmendes** [comment]
Cool, amazing!

**Comment by fabianmendes** [comment]
Excuse me, Luca. Should I download the release or can I git clone the repo instead?

**Comment by Luca1991** [comment]
> Excuse me, Luca. Should I download the release or can I git clone the repo instead?

I don't understand. If you download the archives from the Release section, you will get executable binaries for the currently supported platforms. If you need to build this on your raspberry you have to clone this repo (just clone the master branch, as I'm currently working on other branches), and after setting up Qt , you can start the building process.

EDIT: oh, now I get what you mean: the zip file containing the source code from the release section. No, please don't do that as you will not be able to build it as that archive is pretty old and lacks CMake support!! Just clone the master branch and you should be ok ;)

**Comment by fabianmendes** [comment]
yikes, I got this:
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.18 or higher is required.  You are running version 3.13.4

-- Configuring incomplete, errors occurred!
```
Any idea about solving this?  May this be only for 64-bit?? Or your app runs on 32-bit without any problem?

**Comment by Luca1991** [comment]
Just replace the first line of CMakeLists.txt with:

`cmake_minimum_required(VERSION 3.13)`

Or update your cmake installation to at leat 3.18

**Comment by fabianmendes** [comment]
> Just replace the first line of CMakeLists.txt with:
> 
> `cmake_minimum_required(VERSION 3.13)`
> 
> Or update your cmake installation to at leat 3.18

yeah, I must change it, I just can't upgrade it

**Comment by fabianmendes** [comment]
After detecting some compilations. I got this:
```
CMake Error at CMakeLists.txt:5 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core" with any
  of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/pi/Downloads/git/NDSFactory/build/CMakeFiles/CMakeOutput.log".
```
I think that it's because I didn't this part of the tutorial:  (What do you think?)
![2021-02-26-092210_800x480_scrot](https://user-images.githubusercontent.com/31230743/109305462-1f048100-7814-11eb-993d-dec86c912b68.png)

**Comment by Luca1991** [comment]
That error is telling you that Qt wasn't found on your system. Have you built Qt? A regular build on Raspberry should take a night.

**Comment by fabianmendes** [comment]
> That error is telling you that Qt wasn't found on your system. Have you built Qt? A regular build on Raspberry should take a night.

Nope :L Ok ok, I'll do it now then. I'm a bit scare hahaha

**Comment by Luca1991** [comment]
> > That error is telling you that Qt wasn't found on your system. Have you built Qt? A regular build on Raspberry should take a night.
> 
> Nope :L Ok ok, I'll do it now then. I'm a bit scare hahaha

If you just want to run this on your raspberry I can give you the bin I produced 2 days ago

**Comment by fabianmendes** [comment]
> > > That error is telling you that Qt wasn't found on your system. Have you built Qt? A regular build on Raspberry should take a night.
> > 
> > 
> > Nope :L Ok ok, I'll do it now then. I'm a bit scare hahaha
> 
> If you just want to run this on your raspberry I can give you the bin I produced 2 days ago

:o really?! Yes, please

**Comment by Luca1991** [comment]
> > > > That error is telling you that Qt wasn't found on your system. Have you built Qt? A regular build on Raspberry should take a night.
> > > 
> > > 
> > > Nope :L Ok ok, I'll do it now then. I'm a bit scare hahaha
> > 
> > 
> > If you just want to run this on your raspberry I can give you the bin I produced 2 days ago
> 
> :o really?! Yes, please

Enjoy: http://transfer.sh/GrgPx/NDSFactory.tar.gz

Beware that this isn't really tested. I just built it on my rasp.

Should I close the other issue then? (#7)

**Comment by fabianmendes** [comment]
> > > > > That error is telling you that Qt wasn't found on your system. Have you built Qt? A regular build on Raspberry should take a night.
> > > > 
> > > > 
> > > > Nope :L Ok ok, I'll do it now then. I'm a bit scare hahaha
> > > 
> > > 
> > > If you just want to run this on your raspberry I can give you the bin I produced 2 days ago
> > 
> > 
> > :o really?! Yes, please
> 
> Enjoy: http://transfer.sh/GrgPx/NDSFactory.tar.gz
> 
> Beware that this isn't really tested. I just built it on my rasp.
> 
> Should I close the other issue then? (#7)

Give me a minutes, please

**Comment by fabianmendes** [comment]
How can I run that from the terminal? I can't just double click it, and with `sh` after `chmod a+x` it gave me this: 
```
NDSFactory: 1: NDSFactory: Syntax error: word unexpected (expecting ")")
```

**Comment by Luca1991** [comment]
This is built on AArch64 (ARM 64bit) and will not run on other CPUs

Edit: you should launch this from terminal like any other ELF: ./NDSFactory
This is not an sh script

**Comment by fabianmendes** [comment]
Oh ok ok. Then close the other issue, all right
I'm deploying my OS 64-bit setup. I'll continue with this later! With the 64-bit then. Amazing. I should expect to run this there and that's, it right? (dismissing testing features of course)
Note for #7  and https://github.com/Botspot/pi-apps/issues/394

**Comment by Luca1991** [comment]
Yes correct. Ofc you'll have to know how NDS roms works in order to use this tool.

**Comment by fabianmendes** [comment]
Thanks! Sure :)

**Comment by fabianmendes** [comment]
Hey @Luca1991 I have my Aarch64 setup and Amd64, and I've tried out but got this, it doesn't anything. May you please help me? How should I run this..
![Screenshot from 2021-02-27 09-24-24](https://user-images.githubusercontent.com/31230743/109388768-791e4880-78df-11eb-880a-5cd119769c76.png)

**Comment by Luca1991** [comment]
Why are you trying to launch it like that? Just run it like any other Linux Elf: ./NDSFactory

**Comment by fabianmendes** [comment]
> Why are you trying to launch it like that? Just run it like any other Linux Elf: ./NDSFactory
Because it fails too.
```
mandalorian@basiliscus-ubuntu-desktop64:~/Documents$ ./NDSFactory
bash: ./NDSFactory: No such file or directory
```
Help :(

**Comment by fabianmendes** [comment]
I think I should move that to bash file or something?

**Comment by Luca1991** [comment]
Uhmmm, it looks like your OS isn't recognizing the bin as Elf. Are you sure you are on Raspberry Pi 4??

**Comment by fabianmendes** [comment]
HAHAHAHAH yes of course haha.
Look.
![Screenshot from 2021-02-27 09-47-14](https://user-images.githubusercontent.com/31230743/109388999-cb139e00-78e0-11eb-8b19-71d2a157db5b.png)
Ok, it doesn't show my RPi4 but yes it is haha, other ways is that I try now setting up RPi OS 64-bit instead, it may be the same thing but ubuntu may making things up.
https://live.staticflickr.com/65535/50936327258_1356ddc376.jpg

**Comment by Luca1991** [comment]
> HAHAHAHAH yes of course haha.
> Look.
> ![Screenshot from 2021-02-27 09-47-14](https://user-images.githubusercontent.com/31230743/109388999-cb139e00-78e0-11eb-8b19-71d2a157db5b.png)
> Ok, it doesn't show my RPi4 but yes it is haha, other ways is that I try now setting up RPi OS 64-bit instead, it may be the same thing but ubuntu may making things up.
> https://live.staticflickr.com/65535/50936327258_1356ddc376.jpg

It is so f**king strange what's happening..... Please give raspbian a try and let me know.
Also, if you want contact me using the email on my GitHub profile, I'll give you mi telegram username so we can continue there, as using this issue as a "support thread" is very inconvenient

**Comment by fabianmendes** [comment]
Ok, amazing. Thank you
