### ISSUE TITLE
Preparing install-32 to add it into the Pi-apps

### ISSUE THREAD

**Issue by fabianmendes** [Luca1991/NDSFactory#7]
I want to run this code. NDSFactory, 1st because I want to -haha. 2nd, as this requires compile or pre-installation I prior to keep tracking the steps to do so (make it work), and then turn it into a run same script.
Pi-apps repository: https://github.com/Botspot/pi-apps/
Pi-apps issue [App request] link: https://github.com/Botspot/pi-apps/issues/394

EDIT: Issue #3 serves as helpful instructions to do so. Thanks, @Luca1991 
PS. First of all, I will try to make it up to work on RPi hehe

**Comment by Luca1991** [comment]
Hi, replying from my mobile, so sorry for any typos.

I haven't understood this issue, can you please be more clear in what are you trying to achieve? Thanks :)

**Comment by fabianmendes** [comment]
> Hi, replying from my mobile, so sorry for any typos.
> 
> I haven't understood this issue, can you please be more clear in what are you trying to achieve? Thanks :)

Write a script that once runs it, compiles all it together, e.g. run all the steps you did but with one click... And then, add it to Pi-Apps :)

**Comment by Luca1991** [comment]
Ah, cool! 
I wasn't aware of the existance of that Pi  App Store.
If you are looking for prebuild Qt for Raspberry, you can check this repo: https://github.com/tranter/raspberry-pi-qt-builds
in the releases section, there are some tgz. I haven't tried them, tho. As far as I can see, they are for Raspberry Pi 3.

**Comment by fabianmendes** [comment]
Sorry for asking: may you please help me through the steps you did from the tutorial you have shared with me? I see that there is a lot of packages and installation configuration (I assume that you didn't install additional/optional packages)

I just don't want to mess it up :L

**Comment by Luca1991** [comment]
> Sorry for asking: may you please help me through the steps you did from the tutorial you have shared with me? I see that there is a lot of packages and installation configuration (I assume that you didn't install additional/optional packages)
> 
> I just don't want to mess it up :L

Yes, just tell me which command give you problems and I'll try my best to support you.
I've built the full Qt sdk anyway. I left my Raspberry powered on at night building all the packages.

**Comment by Luca1991** [comment]
Closing this issue (see #3 for more details).
Feel free to reopen this issue (or create another one) if you manage to creare a 1click-build-script for Rasperry :)
